spring:
 application:
   name: distributor
 data:
   mongodb:
     database: distributormovie
     host: 10.20.1.216
     port: "27017"
     uri: mongodb://10.20.1.216/distributormovie
     username: ""

eureka:
 client:
   service-url:
     defaultZone: http://localhost:9083/eureka
   register-with-eureka: "true"
   fetch-registry: "true"
management:
 endpoints:
  web:
   exposure:
    include: "*"
