spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: juggler.stackroute@gmail.com
    password: juggler123
    port: "587"
    protocol: smtp
    test-connection: "false"
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
management:
 endpoints:
  web:
   exposure:
    include: "*"
eureka:
 client:
   service-url:
     defaultZone: http://10.20.1.216:9083/eureka
   register-with-eureka: "true"
   fetch-registry: "true"
bootstrap-id : 10.20.1.16:9092

