spring:
application:
 name: payment
 data:
  mongodb:
   database: payment
   host: 10.20.1.216
   port: "27017"
   uri: mongodb://10.20.1.216/payment
   username: ""
eureka:
client:
 register-with-eureka: "true"
 fetch-registry: "true"
 serviceUrl:
   defaultZone: http://localhost:9084/eureka/
