--- 
eureka: 
  client: 
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl: 
      defaultZone: "http://10.20.1.216:9083/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring: 
  application: 
    name: payment
  data: 
    mongodb: 
      database: payment
      host: 10.20.1.216
      port: "27017"
      uri: "mongodb://10.20.1.216/payment"
      username: ""
bootstrap-id : 10.20.1.16:9092
