
spring:
 data:
  mongodb:
   database: event
   host: localhost
   port: "27017"
   uri: mongodb://10.20.1.216/event
management:
 endpoints:
  web:
   exposure:
    include: "*"
eureka:
 client:
   service-url:
     defaultZone: http://10.20.1.15:9083/eureka
   register-with-eureka: "true"
   fetch-registry: "true"

