spring:
 application:
   name: movie-search
 cloud:
   config:
     uri: http://172.23.239.108:8891
 data:
   mongodb:
     database: moviedb
     host: localhost
     port: "27017"
     uri: mongodb://172.23.239.108/moviedb
     username: ""

eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://172.23.239.116:9090/eureka/
