spring:
 application:
   name: theatre
 data:
   mongodb:
     database: theatre
     host: 10.20.1.216
     port: "27017"
     uri: mongodb://10.20.1.216/theatre
     username: ""
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   service-url:
     defaultZone: http://10.20.1.216:9083/eureka
management:
 endpoints:
  web:
   exposure:
    include: "*"
bootstrap-id : 10.20.1.16:9092
