
eureka: 
  client: 
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl: 
      defaultZone: http://13.126.220.1:9083/eureka/
      
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
        
spring: 
  application: 
    name: booking
  data: 
    mongodb: 
      database: booking
      host: localhost
      port: "27017"
      uri: mongodb://localhost/booking
      username: ""
      
        
 
