
eureka: 
  client: 
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl: 
      defaultZone: http://10.20.1.216:9083/eureka/
      
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
        
spring: 
  application: 
    name: booking
  data: 
    mongodb: 
      database: booking
      host: 10.20.1.216
      port: "27017"
      uri: mongodb://10.20.1.216/booking
      username: ""
      
        
 
