
eureka: 
  client: 
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl: 
      defaultZone: http://13.126.220.1:9083/eureka/
      
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
        
spring: 
  application: 
    name: booking
  data: 
    mongodb: 
      database: booking
      host: 13.127.22.78
      port: "27017"
      uri: mongodb://13.127.22.78/booking
      username: ""
      
    redis:
      repositories:
        enabled: "true"
        
  redis:
    host: localhost

    ssl: 'true'
    port: "6379"


#bootstrap-id : 10.20.1.16:9092
