
spring:
  data:
    mongodb:
      database: userdb
      host: 10.20.1.216
      port: "27017"
      uri: mongodb://10.20.1.216/userdb
      username: ""
  application:
    name: UserProfile

eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://localhost:9083/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
bootstrap-id : 13.232.122.240:9092

